const Language = {
    uz: {
        header: {
            link1: "Uy",
            link2: "Trend",
            link3: "Obunalar",
            link4: "Kutubxona",
            link5: "Tarix",
            link6: "Keyinroq tomosha qiling",
            link7: "Sevimlilar",
            link8: "Yoqdi videolar",
            link9: "Musiqa",
            link10: "O'yinlar",
            link11: "Ko'proq ko'rsatish",
            heading: "Obunalar",
            link12: "Gussi Singleton",
            link13: "Nora Frensis",
            link14: "Belle Briggs",
            link15: "Yunis Kortez",
            link16: "Emma Hanson",
            link17: "Lea Berri",
            link18: "Sozlama",
        },
        hero:{
            input: "Qidirmoq",
            btn: "Chiqish",
        },
        about: {
            heading: "Dolli Bler",
            heading1: "Tavsiya etilgan",
            heading2: "Oziq-ovqat va ichimlik",
            text: "Siz uchun tavsiya etilgan kanal",
            btn: "Obuna 2,3m",
        },
        channel: {
            heading: "Margaret Felps",
            text: "245 ming obuna bo'ldi",
            btn: "Obuna 2,3m",
            link: "Uy",
            link1: "Videolar",
            link2: "Pleylistlar",
            link3: "Kanallar",
            link4: "Munozara",
            link5: "Haqida",
            heading1: "Kompyuteringiz uchun eng yaxshi audio pleer dasturini tanlash",
            text1: "Sizning arzon internetga asoslangan banner reklamangiz u erda qidirilayotgan reklamalardan biriga aylanadi. Bugungi kunda Internet-reklama dunyosi bannerli reklamalar va intruziv qalqib chiquvchi oynalardan tashqari tez rivojlanmoqda. Bayles Internetda reklama uchun keng tarqalgan vosita bannerli reklamalardan foydalanishdir.",
            text2: "11k ko'rish · 6 oy oldin",
            text3: "Tavsiya etilgan kanal", 
            span: "Flora Benson",
            span1: "Violet Kobb",
            span2: "Filip Mullins",
            heading2: "Margaret Felps videolar",
        },
        video: {
            heading: "Do'stim, sen teleskop olasan",
            text: "123 ming ko'rish",
            heading1: "Oziq-ovqat va ichimliklar",
            text1: "2019 yil 14-iyun kuni chop etilgan",
            btn: "Obuna 2,3m",
            text2: "Muvaffaqiyatli marketing rejasi ko'p jihatdan reklama nusxasining tortish kuchiga tayanadi. Natijaga yo'naltirilgan reklama nusxasini yozish qiyin, chunki u iste'molchilarni o'ziga jalb qilishi, jalb qilishi va harakat qilishga ishontirishi kerak. Mukammal reklama nusxasini yozish uchun sehrli formula yo'q; u bir qator omillarga asoslanadi, jumladan, reklama joylashtirish, demografik, hattoki iste'molchining sizning reklamangizni ko'rgandagi kayfiyati",
            link: "Ko'proq ko'rsatish",
            heading2: "Keyingisi",
            heading3: "Avtomatik",
        },
    },
    ru: {
        header: {
            link1: "Дом",
            link2: "В тренде",
            link3: "Подписки",
            link4: "Библиотека",
            link5: "История",
            link6: "Посмотреть позже",
            link7: "Избранное",
            link8: "Понравились видео",
            link9: "Музыка",
            link10: "Игры",
            link11: "Показать больше",
            heading: "Подписки",
            link12: "Гасси Синглтон",
            link13: "Нора Фрэнсис",
            link14: "Белль Бриггс",
            link15: "Юнис Кортес",
            link16: "Эмма Хэнсон",
            link17: "Лия Берри",
            link18: "Параметр",
        },
        hero:{
            input: "Поиск",
            btn: "Выйти",
        },
        about: {
            heading: "Долли Блэр",
            heading1: "Рекомендуется",
            heading2: "Еда и напитки",
            text: "Рекомендуемый канал для вас",
            btn: "Подписаться 2.3m",
        },
        channel: {
            heading: "Маргарет Фелпс",
            text: "245 тыс. подписались",
            btn: "Подписаться 2.3m",
            link: "Дом",
            link1: "Видео",
            link2: "Плейлисты",
            link3: "Каналы",
            link4: "Обсуждение",
            link5: "О",
            heading1: "Выбор лучшего программного обеспечения аудиоплеера для вашего компьютера",
            text1: "Ваша дешевая баннерная реклама в Интернете станет одной из самых востребованных рекламных объявлений. Сегодня мир интернет-рекламы стремительно выходит за рамки баннерной рекламы и навязчивых всплывающих окон. Бэйлс Распространенным средством рекламы в Интернете является использование рекламных баннеров",
            text2: "11 тыс. просмотров · 6 месяцев назад",
            text3: "Рекомендуемый канал", 
            span: "Флора Бенсон",
            span1: "Вайолет Кобб",
            span2: "Филипп Маллинз",
            heading2: "Маргарет Фелпс видео",
        },
        video: {
            heading: "Чувак, ты получишь телескоп",
            text: "123 тысячи просмотров",
            heading1: "Еда, напиток",
            text1: "Опубликовано 14 июня 2019",
            btn: "Подписаться 2,3м",
            text2: "Успешный маркетинговый план во многом зависит от притягательной силы рекламного текста. Написать рекламный текст, ориентированный на результат, сложно, поскольку он должен привлекать, соблазнять и убеждать потребителей совершить действие. Не существует волшебной формулы для написания идеального рекламного текста; он основан на ряде факторов, включая размещение рекламы, демографические данные и даже настроение потребителей, когда они видят вашу рекламу",
            link: "Показать больше",
            heading2: "Следующий",
            heading3: "Автовоспроизведение",
        },
    },
    en: {
        header: {
            link1: "Home",
            link2: "Trending",
            link3: "Subscriptions",
            link4: "Library",
            link5: "History",
            link6: "Watch later",
            link7: "Favorites",
            link8: "Liked videos",
            link9: "Music",
            link10: "Games",
            link11: "Show more",
            heading: "Subscriptions",
            link12: "Gussie Singleton",
            link13: "Nora Francis",
            link14: "Belle Briggs",
            link15: "Eunice Cortez",
            link16: "Emma Hanson",
            link17: "Leah Berry",
            link18: "Setting",
        },
        hero:{
            input: "Search",
            btn: "Log Out",
        },
        about: {
            heading: "Dollie Blair",
            heading1: "Recommended",
            heading2: "Food & Drink",
            text: "Recommended channel for you",
            btn: "Subscribe 2.3m",
        },
        channel: {
            heading: "Margaret Phelps",
            text: "245K subscribed",
            btn: "Subscribe 2.3m",
            link: "Home",
            link1: "Videos",
            link2: "Playlists",
            link3: "Channels",
            link4: "Discussion",
            link5: "About",
            heading1: "Choosing The Best Audio Player Software For Your Computer",
            text1: "Your cheap internet-based banner advertising will become one of the sought after ads there are. Today, the world of Internet advertising is rapidly evolving beyond banner ads and intrusive pop-ups. Bayles A common medium for advertising on the Internet is the use of banner ads",
            text2: "11k views · 6 months ago",
            text3: "Recommended channel", 
            span: "Flora Benson",
            span1: "Violet Cobb",
            span2: "Phillip Mullins",
            heading2: "Margaret Phelps videos",
        },
        video: {
            heading: "Dude You Re Getting A Telescope",
            text: "123k views",
            heading1: "Food & Drink",
            text1: "Published on 14 Jun 2019",
            btn: "Subscribe 2.3m",
            text2: "A successful marketing plan relies heavily on the pulling-power of advertising copy. Writing result-oriented ad copy is difficult, as it must appeal to, entice, and convince consumers to take action. There is no magic formula to write perfect ad copy; it is based on a number of factors, including ad placement, demographics, even the consumer’s mood when they see your ad",
            link: "Show more",
            heading3: "Автовоспроизведение",
        },
    },
}
export default Language;